services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=HallOfFame_DB;Username=postgres;Password=root
    container_name: Hall_Of_Fame_web_api
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: HallOfFame_DB
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgresql
volumes:
  db_data:
